2018-07-15 23:10:30,874 ERROR: Exception on /user/saswatlevin/ [GET] [in c:\microblog\virtualenv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\virtualenv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\virtualenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 154, in user
    next_url=next_url,prev_url=prev_url)
  File "c:\microblog\virtualenv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\microblog\virtualenv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\microblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\microblog\app\templates\user.html", line 21, in block "content"
    {% elif not current_user.follow(user) %}
  File "C:\microblog\app\models.py", line 47, in follow
    if not user.is_following(user):
  File "C:\microblog\app\models.py", line 55, in is_following
    return self.followed.filter(followers.c.followed_id==user.id).count > 0
TypeError: '>' not supported between instances of 'method' and 'int'
2018-07-15 23:12:15,160 INFO: Microblog startup [in C:\microblog\app\__init__.py:71]
2018-07-15 23:14:20,383 INFO: Microblog startup [in C:\microblog\app\__init__.py:71]
2018-07-15 23:22:43,532 INFO: Microblog startup [in C:\microblog\app\__init__.py:71]
2018-07-15 23:23:44,530 INFO: Microblog startup [in C:\microblog\app\__init__.py:71]
2018-07-15 23:25:53,205 INFO: Microblog startup [in C:\microblog\app\__init__.py:71]
2018-07-15 23:32:24,492 INFO: Microblog startup [in C:\microblog\app\__init__.py:71]
2018-07-15 23:32:42,599 ERROR: Exception on / [GET] [in c:\microblog\virtualenv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\virtualenv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\virtualenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 42, in index
    return render_template('index.html',title='Home',form=form,posts=posts.items,prev_url=prev_url,next_url=next_url)
  File "c:\microblog\virtualenv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\microblog\virtualenv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\microblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\microblog\app\templates\index.html", line 27, in block "content"
    {% if not current_user.follow(user) %}
  File "C:\microblog\app\models.py", line 47, in follow
    if not user.is_following(user):
jinja2.exceptions.UndefinedError: 'user' is undefined
2018-07-15 23:34:49,692 INFO: Microblog startup [in C:\microblog\app\__init__.py:71]
2018-07-15 23:35:07,179 ERROR: Exception on / [GET] [in c:\microblog\virtualenv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\virtualenv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\virtualenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\virtualenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 42, in index
    return render_template('index.html',title='Home',form=form,posts=posts.items,prev_url=prev_url,next_url=next_url)
  File "c:\microblog\virtualenv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\microblog\virtualenv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\microblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\microblog\app\templates\index.html", line 27, in block "content"
    <p><a href="{{url_for('follow',username=user.username)}}">Follow</a></p>
  File "c:\microblog\virtualenv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2018-07-15 23:36:01,384 INFO: Microblog startup [in C:\microblog\app\__init__.py:71]
